name: Semifold CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  status:
    name: Semifold CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Semifold
        run: cargo install semifold
      - name: Semifold CI
        run: semifold ci --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.crate_token }}
